main: de.raidcraft.combatbar.RCHotbarPlugin
name: RCCombatBar
version: ${project.version}#${build.number}
description: Implementation of Combat Bar.
author: Silthus
website: http://www.raid-craft.de
depend: [RaidCraft-API]
softdepend: [RCGraveyards]
database: false
api-version: 1.13